name: Windows Self-Hosted Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Настройка окружения UTF-8
      - name: Configure UTF-8 environment
        run: |
          [System.Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          [System.Console]::InputEncoding = [System.Text.Encoding]::UTF8
          chcp 65001
          echo "PYTHONIOENCODING=UTF-8" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PYTHONUTF8=1" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      # Кэширование виртуального окружения
      - name: Cache venv
        uses: actions/cache@v3
        id: cache-venv
        with:
          path: .venv
          key: venv-${{ runner.os }}-py3.10-${{ hashFiles('requirements.txt') }}-${{ hashFiles('.github/workflows/*.yml') }}

      # Установка системных зависимостей
      - name: Install Windows Dependencies
        run: |
          choco install ffmpeg pngquant imagemagick git-lfs nodejs -y --no-progress
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv
          ffmpeg -version
          pngquant --version
          magick --version
          git lfs version
          node --version

      # Установка vgmstream
      - name: Install vgmstream
        run: |
          Invoke-WebRequest -Uri "https://github.com/vgmstream/vgmstream-releases/releases/download/nightly/vgmstream-win64.zip" -OutFile "vgmstream.zip"
          Expand-Archive -Path "vgmstream.zip" -DestinationPath "bin" -Force
          Remove-Item -Path "vgmstream.zip"
          echo "$PWD\bin" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8

      # Настройка PNPM
      - name: Setup PNPM
        run: |
          npm install -g pnpm
          pnpm -v

      # Восстановление кэша ресурсов
      - name: Restore Cached Resources
        id: restore-gf-downloader-resources
        uses: actions/cache/restore@v4
        with:
          path: unpack/downloader/output
          key: gf-downloader-resources-${{ runner.os }}-${{ github.sha }}

      # Настройка Python окружения
      - name: Setup Python Environment
        run: |
          python -m venv .venv
          .\.venv\Scripts\activate
          python -m pip install --upgrade pip wheel setuptools
          pip install pdm
          cd unpack
          pdm config venv.in_project true
          pdm install
          pip install --force-reinstall pyjson5 chardet
          pip install -r downloader/requirements.txt

      # Загрузка ресурсов (если кэш не найден)
      - name: Download Resources (if cache missed)
        if: steps.restore-gf-downloader-resources.outputs.cache-hit != 'true'
        env:
          GD_DATA: ${{ secrets.GD_DATA }}
        run: |
          cd unpack/downloader
          if (!(Test-Path "config.json5")) {
            Write-Error "Файл config.json5 не найден!"
            exit 1
          }
          python downloader.py --folder-id "1YPAEYsvjs8UjMLNogu_VtUIWW0rr4-Ls"

      # Сохранение кэша ресурсов
      - name: Cache Downloaded Resources
        uses: actions/cache/save@v4
        if: always()
        with:
          path: unpack/downloader/output
          key: ${{ steps.restore-gf-downloader-resources.outputs.cache-primary-key }}

      # Обработка изображений
      - name: Restore Cached Images
        id: restore-image-resources
        uses: actions/cache/restore@v4
        with:
          path: unpack/images
          key: gf-image-resources-${{ runner.os }}-${{ github.sha }}

      - name: Unpack images
        run: |
          cd unpack
          .\.venv\Scripts\activate
          $env:PYTHONPATH = "$pwd\src"
          python tests/test_backgrounds.py
          python tests/test_characters.py

      - name: Cache Images
        uses: actions/cache/save@v4
        if: always()
        with:
          path: unpack/images
          key: ${{ steps.restore-image-resources.outputs.cache-primary-key }}

      # Обработка аудио
      - name: Restore Cached Audio
        id: restore-audio-resources
        uses: actions/cache/restore@v4
        with:
          path: unpack/audio
          key: gf-audio-resources-${{ runner.os }}-${{ github.sha }}

      - name: Unpack audio
        run: |
          cd unpack
          .\.venv\Scripts\activate
          $env:PYTHONPATH = "$pwd\src"
          python tests/test_audio.py

      - name: Cache Audio
        uses: actions/cache/save@v4
        if: always()
        with:
          path: unpack/audio
          key: ${{ steps.restore-audio-resources.outputs.cache-primary-key }}

      # Распаковка ресурсов
      - name: Unpack resources
        run: |
          $ErrorActionPreference = "Stop"
          cd unpack
          
          # Проверка установки chardet
          .\.venv\Scripts\activate
          python -c "import chardet; print(f'chardet {chardet.__version__} installed')"
          
          # Запуск распаковки
          python -m gfunpack downloader/output -o .
          
          # Проверка файлов
          $requiredFiles = @(
              "audio/audio.json",
              "images/backgrounds.json",
              "images/characters.json",
              "stories/stories.json",
              "stories/chapters.json"
          )
          foreach ($file in $requiredFiles) {
              if (-not (Test-Path $file)) {
                  Write-Host "::warning file=$file::File $file not found"
              }
          }

      # Перемещение ресурсов
      - name: Move resources
        run: |
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          cd unpack
          
          # Создание директорий
          New-Item -ItemType Directory -Path "../src/assets" -Force | Out-Null
          New-Item -ItemType Directory -Path "../public" -Force | Out-Null
          
          # Копирование JSON файлов
          $jsonFiles = @(
              "audio/audio.json",
              "images/backgrounds.json",
              "images/characters.json",
              "stories/stories.json",
              "stories/chapters.json"
          )
          foreach ($file in $jsonFiles) {
              if (Test-Path $file)) {
                  Copy-Item $file "../src/assets" -Force
              }
          }
          
          # Перемещение папок
          $folders = @("audio", "images", "stories")
          foreach ($folder in $folders) {
              if (Test-Path $folder)) {
                  Move-Item $folder "../public" -Force
              }
          }

      # Сборка сайта
      - name: Build site
        run: |
          # Проверка файлов
          $requiredAssets = @(
              "src/assets/audio.json",
              "src/assets/backgrounds.json",
              "src/assets/characters.json",
              "src/assets/stories.json",
              "src/assets/chapters.json"
          )
          foreach ($file in $requiredAssets) {
              if (-not (Test-Path $file)) {
                  Write-Host "::error file=$file::Required file missing"
                  exit 1
              }
          }
          
          # Сборка
          pnpm install --frozen-lockfile
          pnpm build-index
          pnpm build

      # Публикация
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: dist