name: Windows Self-Hosted Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Проверка дискового пространства
      - name: Check Disk Space
        run: |
          Get-Volume | Format-Table -AutoSize DriveLetter, SizeRemaining, Size

      # Установка системных зависимостей
      - name: Install System Tools
        run: |
          choco install -y ffmpeg pngquant imagemagick git-lfs nodejs python --version=3.10.0
          refreshenv
          git lfs install
          git lfs track "*.wav" "*.mp3" "*.png" "*.jpg" "*.webp" "*.zip"
          git add .gitattributes

      # Установка vgmstream
      - name: Install vgmstream
        run: |
          Invoke-WebRequest -Uri "https://github.com/vgmstream/vgmstream-releases/releases/download/nightly/vgmstream-win64.zip" -OutFile "vgmstream.zip"
          Expand-Archive -Path "vgmstream.zip" -DestinationPath "bin" -Force
          Remove-Item -Path "vgmstream.zip"
          echo "$PWD\bin" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8

      # Установка PNPM
      - name: Setup PNPM
        run: |
          npm install -g pnpm
          pnpm -v

      # Кэширование ресурсов
      - name: Restore Resources Cache
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            unpack/downloader/output
          key: gf-resources-${{ runner.os }}-${{ github.sha }}

      # Настройка Python окружения
      - name: Setup Python Environment
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          .\.venv\Scripts\activate
          pip install --force-reinstall chardet==5.2.0 UnityPy pyjson5
          pip install -r unpack/downloader/requirements.txt
          
          # Проверка установки
          python -c "import chardet; print(f'chardet path: {chardet.__file__}')"
          python -m pip list

      # Загрузка ресурсов (если нет в кэше)
      - name: Download Resources
        if: steps.restore-cache.outputs.cache-hit != 'true'
        env:
          GD_DATA: ${{ secrets.GD_DATA }}
        run: |
          cd unpack/downloader
          if (!(Test-Path "config.json5")) {
            Write-Error "config.json5 not found!"
            exit 1
          }
          python downloader.py --folder-id "1YPAEYsvjs8UjMLNogu_VtUIWW0rr4-Ls"

      # Сохранение в кэш
      - name: Save Resources Cache
        uses: actions/cache/save@v4
        continue-on-error: true
        with:
          path: |
            unpack/downloader/output
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}

      # Распаковка ресурсов
      - name: Unpack Resources
        run: |
          .\.venv\Scripts\activate
          cd unpack
          python -m gfunpack downloader/output -o .
          
          # Проверка файлов
          if (!(Test-Path "audio/audio.json")) { throw "audio.json not created!" }
          if (!(Test-Path "images/backgrounds.json")) { throw "backgrounds.json not created!" }
          if (!(Test-Path "images/characters.json")) { throw "characters.json not created!" }

      # Перенос ресурсов
      - name: Move Resources
        run: |
          cd unpack
          mkdir -p ../src/assets
          cp audio/audio.json images/backgrounds.json images/characters.json stories/stories.json stories/chapters.json ../src/assets
          mkdir -p ../public
          mv audio ../public
          mv images ../public
          mv stories ../public

      # Сборка проекта
      - name: Install Project Dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build Project
        run: |
          pnpm build-index
          pnpm build

      # Деплой
      - name: Deploy to Cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: dist