name: Build Documentation

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log Disk Space
        run: df -h

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false
          swap-storage: false

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg pngquant imagemagick libfuse2
          wget https://github.com/vgmstream/vgmstream-releases/releases/download/nightly/vgmstream-linux-cli.tar.gz
          tar -zxf vgmstream-linux-cli.tar.gz
          mkdir -p bin
          mv vgmstream-cli bin/
          wget https://imagemagick.org/archive/binaries/magick -O bin/magick
          chmod a+x bin/*
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Setup Python Environment
        run: |
          cd unpack
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install pyjson5 pillow

      - name: Restore Downloader Cache
        id: restore-downloader
        uses: actions/cache/restore@v4
        with:
          path: |
            unpack/downloader/output
            unpack/downloader/resdata
          key: ${{ runner.os }}-gf-downloader-${{ hashFiles('unpack/downloader/config.json5') }}
          restore-keys: |
            ${{ runner.os }}-gf-downloader-

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install Python Dependencies
        run: |
          cd unpack
          source .venv/bin/activate
          pdm install
          pip install -r downloader/requirements.txt

      - name: Fix Logging Configuration
        run: |
          cd unpack/downloader
          mkdir -p logger_tt
          echo '{"version":1,"disable_existing_loggers":false}' > logger_tt/log_config.json
          sed -i "s/setup_mp_logging()/import logging; logging.basicConfig(level=logging.INFO)/" downloader.py

      - name: Download Resources
        if: steps.restore-downloader.outputs.cache-hit != 'true'
        env:
          GD_DATA: ${{ secrets.GD_DATA }}
        run: |
          cd unpack/downloader
          
          if [ ! -f "config.json5" ]; then
            echo "::error::Файл config.json5 не найден!"
            exit 1
          fi

          ln -sf config.json5 config.json
          pip install -r requirements.txt
#
#          # Добавлен --clear-cache при первом запуске
#          python downloader.py --folder-id "1YPAEYsvjs8UjMLNogu_VtUIWW0rr4-Ls" --clear-cache

          if [ ! -f "resdata/us_resdata.json" ]; then
            echo "::error::Ошибка загрузки файлов"
            exit 1
          fi
          echo "::notice::Загрузка завершена успешно"

      - name: Save Downloader Cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            unpack/downloader/output
            unpack/downloader/resdata
          key: ${{ steps.restore-downloader.outputs.cache-primary-key }}

      - name: Restore Image Cache
        id: restore-images
        uses: actions/cache/restore@v4
        with:
          path: unpack/images
          key: ${{ runner.os }}-gf-images-${{ hashFiles('unpack/downloader/config.json5') }}-${{ hashFiles('unpack/tests/test_backgrounds.py') }}
          restore-keys: |
            ${{ runner.os }}-gf-images-

      - name: Process Images
        if: steps.restore-downloader.outputs.cache-hit != 'true' || steps.restore-images.outputs.cache-hit != 'true'
        run: |
          cd unpack
          source .venv/bin/activate
          python tests/test_backgrounds.py
          python tests/test_characters.py

      - name: Save Image Cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: unpack/images
          key: ${{ steps.restore-images.outputs.cache-primary-key }}

      - name: Restore Audio Cache
        id: restore-audio
        uses: actions/cache/restore@v4
        with:
          path: unpack/audio
          key: ${{ runner.os }}-gf-audio-${{ hashFiles('unpack/downloader/config.json5') }}-${{ hashFiles('unpack/tests/test_audio.py') }}
          restore-keys: |
            ${{ runner.os }}-gf-audio-

      - name: Process Audio
        if: steps.restore-downloader.outputs.cache-hit != 'true' || steps.restore-audio.outputs.cache-hit != 'true'
        run: |
          cd unpack
          source .venv/bin/activate
          python tests/test_audio.py

      - name: Save Audio Cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: unpack/audio
          key: ${{ steps.restore-audio.outputs.cache-primary-key }}

      - name: Unpack All Resources
        run: |
          cd unpack
          source .venv/bin/activate
          python -m gfunpack downloader/output -o .

      - name: Prepare Final Assets
        run: |
          cd unpack
          mkdir -p ../src/assets ../public
          cp audio/audio.json images/backgrounds.json images/characters.json stories/stories.json stories/chapters.json ../src/assets/
          mv audio images stories ../public/

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0
          run_install: true

      - name: Build Frontend
        run: |
          pnpm build-index
          pnpm build

      - name: Deploy to Cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: dist