name: Run Audio Script

on:
  workflow_dispatch:
  push:

jobs:
  run-audio:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure system encoding
        run: |
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          chcp 65001 | Out-Null
          git config --global core.quotepath false
          $env:PYTHONUTF8 = "1"
          $env:LC_ALL = "C.UTF-8"
          $env:ACTIONS_ALLOW_UNSECURE_COMMANDS = "true"

      - name: Install Windows Dependencies
        run: |
          choco install ffmpeg -y --no-progress
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv

      - name: Install vgmstream
        run: |
          Invoke-WebRequest -Uri "https://github.com/vgmstream/vgmstream-releases/releases/download/nightly/vgmstream-win64.zip" -OutFile "vgmstream.zip"
          Expand-Archive -Path "vgmstream.zip" -DestinationPath "bin" -Force
          Remove-Item -Path "vgmstream.zip"
          echo "$PWD\bin" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8

      - name: Verify tools
        run: |
          Write-Host "=== Tool versions ==="
          ffmpeg -version
          & "C:\vgmstream\vgmstream-cli.exe" -V
          
          Write-Host "=== PATH contents ==="
          $env:PATH -split ';' | Where-Object { $_ -ne '' } | ForEach-Object { Write-Host $_ }

      - name: Run audio tests
        run: |
          # Явно указываем путь к vgmstream-cli в коде
          $env:VGMSTREAM_PATH = "C:\vgmstream\vgmstream-cli.exe"
          cd unpack
          python tests/test_audio.py