name: Run Audio Script

on:
  workflow_dispatch:
  push:

jobs:
  run-audio:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          # Установка Python-зависимостей
          pip install UnityPy chardet tqdm
          cd unpack
          pip install -e .

          # Проверка и установка ffmpeg (если еще не установлен)
          if (-not (Get-Command ffmpeg -ErrorAction SilentlyContinue)) {
              choco install ffmpeg -y
          }

          # Установка vgmstream из альтернативного источника
          $vgmstreamUrl = "https://github.com/vgmstream/vgmstream-releases/releases/download/r1882/vgmstream-win64.zip"
          $tempDir = "C:\vgmstream"
          New-Item -ItemType Directory -Path $tempDir -Force
          
          try {
              # Пробуем скачать через прямой URL
              Invoke-WebRequest -Uri $vgmstreamUrl -OutFile "$tempDir\vgmstream.zip"
          } catch {
              # Если не получилось, используем альтернативный источник
              $vgmstreamUrl = "https://www.files.vgmstream.org/win64/vgmstream-win64.zip"
              Invoke-WebRequest -Uri $vgmstreamUrl -OutFile "$tempDir\vgmstream.zip"
          }
          
          Expand-Archive -Path "$tempDir\vgmstream.zip" -DestinationPath $tempDir
          $env:PATH += ";$tempDir"
          echo "$tempDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Verify tools
        run: |
          # Проверка установленных инструментов
          ffmpeg -version
          vgmstream-cli -V
          Write-Host "Current PATH: $env:PATH"

      - name: Verify files exist
        run: |
          if (-not (Test-Path "unpack/downloader/output/AVG.acb.dat")) {
              Write-Host "::error::Missing AVG.acb.dat in downloader/output"
              exit 1
          }

      - name: Run audio.py
        run: |
          cd unpack/tests
          python test_audio.py