name: Audio Script Debug

on:
  workflow_dispatch:
    inputs:
      skip_steps:
        description: "Skip steps (comma separated)"
        required: false
        default: ""

jobs:
  audio-debug:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup debug environment
        run: |
          # Установка только необходимых зависимостей
          choco install ffmpeg -y --no-progress
          pip install tqdm

          # Скачиваем vgmstream
          $vgmUrl = "https://github.com/vgmstream/vgmstream/releases/download/r1882/vgmstream-win64.zip"
          Invoke-WebRequest -Uri $vgmUrl -OutFile "vgmstream.zip"
          Expand-Archive -Path "vgmstream.zip" -DestinationPath "vgmstream" -Force
          echo "$PWD\vgmstream\test" >> $env:GITHUB_PATH

      - name: Run isolated audio test
        run: |
          # Создаем тестовую среду
          New-Item -ItemType Directory -Force -Path "test_audio"
          Copy-Item "unpack/downloader/output/AVG.acb.dat" -Destination "test_audio/"
          Copy-Item "unpack/downloader/output/BGM.acb.dat" -Destination "test_audio/"

          # Запускаем audio.py напрямую
          python -c "
          import sys
          sys.path.append('unpack/src')
          from gfunpack import audio
          
          bgm = audio.BGM(
              directory='test_audio',
              destination='test_output',
              force=True,
              concurrency=1,
              clean=False
          )
          bgm.save()
          print('=== DEBUG INFO ===')
          print('Extracted files:', list(bgm.extracted.items())[:3])
          print('Output exists:', (Path('test_output/audio.json').exists()))
          "

          # Детальная проверка результатов
          if (Test-Path "test_output/audio.json") {
              Write-Host "SUCCESS: audio.json created"
              Get-Content "test_output/audio.json" | Select-Object -First 20
          } else {
              Write-Host "::error::audio.json not created"
              Get-ChildItem "test_output" -Recurse | Format-Table FullName
              exit 1
          }