name: Run Audio Script

on:
  workflow_dispatch:
  push:

jobs:
  run-audio:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure system encoding
        run: |
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          chcp 65001 | Out-Null
          git config --global core.quotepath false
          $env:PYTHONUTF8 = "1"
          $env:LC_ALL = "C.UTF-8"
          $env:ACTIONS_ALLOW_UNSECURE_COMMANDS = "true"

      - name: Install Windows Dependencies
        run: |
          choco install ffmpeg -y --no-progress
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv

      - name: Install vgmstream (fixed method)
        run: |
          # Создаем директорию для vgmstream
          $vgmDir = "C:\vgmstream"
          New-Item -ItemType Directory -Path $vgmDir -Force

          # Используем рабочий URL из официального репозитория
          $vgmUrl = "https://github.com/vgmstream/vgmstream/releases/download/r1882/vgmstream-cli.zip"
          
          # Скачиваем архив
          try {
              Invoke-WebRequest -Uri $vgmUrl -OutFile "$vgmDir\vgmstream.zip" -ErrorAction Stop
          } catch {
              Write-Host "::error::Failed to download vgmstream: $($_.Exception.Message)"
              exit 1
          }

          # Распаковываем
          Expand-Archive -Path "$vgmDir\vgmstream.zip" -DestinationPath $vgmDir -Force
          Remove-Item -Path "$vgmDir\vgmstream.zip" -Force

          # Добавляем в PATH (новый метод)
          echo "$vgmDir" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
          $env:PATH = "$vgmDir;$env:PATH"

          # Проверяем установку
          Write-Host "Testing vgmstream installation..."
          & "$vgmDir\vgmstream-cli.exe" -V
          if ($LASTEXITCODE -ne 0) {
              Write-Host "::error::vgmstream-cli verification failed"
              exit 1
          }

      - name: Verify tools
        run: |
          Write-Host "=== Tool versions ==="
          ffmpeg -version
          & "C:\vgmstream\vgmstream-cli.exe" -V
          
          Write-Host "=== PATH contents ==="
          $env:PATH -split ';' | Where-Object { $_ -ne '' } | ForEach-Object { Write-Host $_ }

      - name: Run audio tests
        run: |
          # Явно указываем путь к vgmstream-cli в коде
          $env:VGMSTREAM_PATH = "C:\vgmstream\vgmstream-cli.exe"
          cd unpack
          python tests/test_audio.py