name: Run Audio Script

on:
  workflow_dispatch:
  push:

jobs:
  run-audio:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install dependencies
        run: |
          # Python dependencies
          pip install UnityPy chardet tqdm
          cd unpack
          pip install -e .

          # Install ffmpeg
          choco install ffmpeg -y

          # Install vgmstream manually
          $vgmstreamUrl = "https://github.com/vgmstream/vgmstream/releases/download/r1882/vgmstream-win64.zip"
          $tempDir = "C:\temp"
          New-Item -ItemType Directory -Path $tempDir -Force
          Invoke-WebRequest -Uri $vgmstreamUrl -OutFile "$tempDir\vgmstream.zip"
          Expand-Archive -Path "$tempDir\vgmstream.zip" -DestinationPath "$tempDir\vgmstream"
          echo "$tempDir\vgmstream\test" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          # Refresh environment
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv

      - name: Verify tools
        run: |
          ffmpeg -version
          vgmstream-cli -V

      - name: Verify files exist
        run: |
          if (-not (Test-Path "unpack/downloader/output/AVG.acb.dat")) {
              Write-Host "::error::Missing AVG.acb.dat in downloader/output"
              exit 1
          }

      - name: Run audio.py
        run: |
          cd unpack/tests
          python test_audio.py