name: Run Audio Script

on:
  workflow_dispatch:  # Только ручной запуск через UI GitHub
  push:

jobs:
  run-audio:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install UnityPy chardet tqdm
          sudo apt-get install -y ffmpeg vgmstream-cli  # Для Linux
          # Для Windows (если runner Windows):
          # choco install ffmpeg vgmstream -y
          cd unpack
          pip install -e .

      - name: Verify files exist
        run: |
          ls -R unpack/downloader/output/  # Проверка структуры папок
          if [ ! -f "unpack/downloader/output/AVG.acb.dat" ]; then
              echo "::error::Missing AVG.acb.dat in downloader/output"
              exit 1
          fi

      - name: Run audio.py
        run: |
          cd unpack/tests
          python -c "from pathlib import Path; print('Current dir:', Path.cwd())"  # Логирование текущей директории
          python test_audio.py