name: Run Audio Script

on:
  workflow_dispatch:

jobs:
  run-audio:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install UnityPy chardet tqdm
          cd unpack
          pip install -e .

      - name: Run audio.py
        run: |
          cd unpack
          export PYTHONPATH="$PYTHONPATH:$GITHUB_WORKSPACE/unpack/src"
          python tests/test_audio.py
