name: Run Audio Script

on:
  workflow_dispatch:
  push:

jobs:
  run-audio:
    runs-on: self-hosted  # Убедитесь, что это Windows-раннер

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          # Установка Python-зависимостей
          pip install UnityPy chardet tqdm
          cd unpack
          pip install -e .

          # Установка ffmpeg и vgmstream для Windows
          choco install ffmpeg -y
          choco install vgmstream -y
          refreshenv

      - name: Verify files exist
        run: |
          # Проверка существования файлов (PowerShell)
          if (-not (Test-Path "unpack/downloader/output/AVG.acb.dat")) {
              Write-Host "::error::Missing AVG.acb.dat in downloader/output"
              exit 1
          }

      - name: Run audio.py
        run: |
          cd unpack/tests
          python test_audio.py