name: Run Audio Script

on:
  workflow_dispatch:

jobs:
  run-audio:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install UnityPy chardet tqdm
          cd unpack
          pip install -e .

      - name: Verify files exist
        run: |
          # Проверяем существование нужных файлов
          if (-not (Test-Path "unpack/downloader/output/AVG.acb.dat")) {
              Write-Host "::error::Missing AVG.acb.dat in downloader/output"
              exit 1
          }

      - name: Run audio.py
        run: |
          cd $env:GITHUB_WORKSPACE
          $env:PYTHONPATH = "$env:PYTHONPATH;$env:GITHUB_WORKSPACE/unpack/src"
          python unpack/tests/test_audio.py
