name: Run Audio Script

on:
  workflow_dispatch:
  push:

jobs:
  run-audio:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure system encoding
        run: |
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          chcp 65001 | Out-Null
          git config --global core.quotepath false
          $env:PYTHONUTF8 = "1"
          $env:LC_ALL = "C.UTF-8"
          $env:ACTIONS_ALLOW_UNSECURE_COMMANDS = "true"

      - name: Install Windows Dependencies
        run: |
          choco install ffmpeg -y --no-progress
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv

      - name: Install vgmstream
        run: |
          # Устанавливаем в C:\vgmstream для единообразия
          $vgmDir = "C:\vgmstream"
          New-Item -ItemType Directory -Path $vgmDir -Force
          
          Invoke-WebRequest -Uri "https://github.com/vgmstream/vgmstream-releases/releases/download/nightly/vgmstream-win64.zip" -OutFile "$vgmDir\vgmstream.zip"
          Expand-Archive -Path "$vgmDir\vgmstream.zip" -DestinationPath $vgmDir -Force
          Remove-Item -Path "$vgmDir\vgmstream.zip" -Force
          
          # Добавляем в PATH
          echo "$vgmDir" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
          $env:PATH = "$vgmDir;$env:PATH"

      - name: Verify tools
        run: |
          Write-Host "=== Tool versions ==="
          ffmpeg -version
          
          # Проверяем vgmstream по полному пути
          $vgmPath = "C:\vgmstream\vgmstream-cli.exe"
          if (Test-Path $vgmPath) {
              & $vgmPath -V
          } else {
              Write-Host "::error::vgmstream-cli.exe not found at $vgmPath"
              Get-ChildItem "C:\vgmstream" -Recurse | Format-Table FullName
              exit 1
          }
          
          Write-Host "=== PATH contents ==="
          $env:PATH -split ';' | Where-Object { $_ -ne '' } | ForEach-Object { Write-Host $_ }

      - name: Run audio tests
        run: |
          # Явно указываем путь к vgmstream-cli
          $env:VGMSTREAM_PATH = "C:\vgmstream\vgmstream-cli.exe"
          cd unpack
          python tests/test_audio.py